export const PHISHING_INTERACTIONS = {
  EMAIL_OPENED: 'EMAIL_OPENED',
  INSPECT_SENDER: 'INSPECT_SENDER',
  REPORT_PHISHING: 'REPORT_PHISHING',
  LEGIT_LINK_CLICKED: 'LEGIT_LINK_CLICKED',
  FAKE_LINK_CLICKED: 'FAKE_LINK_CLICKED',
  CREDENTIALS_ENTERED: 'CREDENTIALS_ENTERED',
};
